name: Centralized PR Automation

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Feature branch to create PR from'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Feature Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name }}
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          branch: ${{ github.event.inputs.branch_name }}
          title: "Automated PR for ${{ github.event.inputs.branch_name }}"
          body: |
            Automated PR created from **${{ github.event.inputs.branch_name }}**.
            Pushed by: ${{ github.actor }}
          labels: auto-generated
          draft: false
