name: Revert-from-dev

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Feature branch whose last squash merge into dev should be reverted (e.g., feature/30)"
        required: true

jobs:
  revert-squash-commit:
    name: Revert last squash merge from feature branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Normalize branch name
        id: normalize
        run: |
          BRANCH_NAME=$(echo "${{ github.event.inputs.branch_name }}" | sed 's#^remotes/origin/##')
          if [[ ! "$BRANCH_NAME" =~ ^[a-zA-Z0-9._/-]+$ ]]; then
            echo "Error: Invalid branch name '$BRANCH_NAME'"
            exit 1
          fi
          echo "normalized_branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Switch to dev
        run: |
          git fetch origin dev
          git checkout dev
          git pull origin dev

      - name: Find latest squash merge commit for this feature
        id: find_commit
        run: |
          PATTERN="${{ steps.normalize.outputs.normalized_branch }}"
          COMMIT=$(git log dev --grep="from .*$PATTERN" --pretty=%H -n 1)

          if [ -z "$COMMIT" ]; then
            echo "Error: No squash merge commit found in dev for '$PATTERN'"
            exit 1
          fi

          echo "commit_sha=$COMMIT" >> $GITHUB_OUTPUT

      - name: Check if commit already reverted
        id: check_revert
        run: |
          COMMIT="${{ steps.find_commit.outputs.commit_sha }}"
          FEATURE="${{ steps.normalize.outputs.normalized_branch }}"

          LATEST_ACTION=$(git log dev --grep="from .*$FEATURE\|Revert \"$FEATURE\"" --pretty=%s -n 1)

          if echo "$LATEST_ACTION" | grep -q "Revert \"$FEATURE\""; then
            echo "Error: Last operation for '$FEATURE' is already a revert."
            echo "revert_status=already_reverted" >> $GITHUB_OUTPUT
            exit 1
          fi

          if echo "$LATEST_ACTION" | grep -q "from .*$FEATURE"; then
            echo "revert_status=not_reverted" >> $GITHUB_OUTPUT
          else
            echo "Error: Could not determine last commit action."
            exit 1
          fi

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Attempt revert
        id: revert
        run: |
          COMMIT="${{ steps.find_commit.outputs.commit_sha }}"
          FEATURE="${{ steps.normalize.outputs.normalized_branch }}"

          echo "Reverting commit $COMMIT for feature '$FEATURE'..."

          set +e
          git revert --no-commit "$COMMIT"
          STATUS=$?
          set -e

          if [ $STATUS -ne 0 ]; then
            git revert --abort
            echo "conflict=true" >> $GITHUB_OUTPUT
            exit 1
          fi

          git commit -m "Revert \"$FEATURE\""
          echo "conflict=false" >> $GITHUB_OUTPUT

      - name: Push revert to dev
        if: steps.revert.outputs.conflict == 'false'
        run: |
          git pull origin dev --rebase
          git push origin dev
