name: manual-revert-workflow

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch name to find and revert its merge commit in dev (e.g., f5)"
        required: true

jobs:
  revert-merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper commit lookup
        token: ${{ secrets.PAT }}  # Use PAT for checkout to ensure push permissions
        
    - name: List all branches for debugging
      run: git branch -a
      
    - name: Normalize branch name
      id: normalize
      run: |
        # Strip 'remotes/origin/' prefix if present, otherwise use input as-is
        BRANCH_NAME=$(echo "${{ github.event.inputs.branch_name }}" | sed 's#^remotes/origin/##')
        echo "normalized_branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
        
    - name: Validate branch exists
      run: |
        if ! git show-ref --quiet refs/remotes/origin/${{ steps.normalize.outputs.normalized_branch }}; then
          echo "Error: Remote branch 'origin/${{ steps.normalize.outputs.normalized_branch }}' does not exist. Available branches:"
          git branch -a
          exit 1
        fi
        
    - name: Switch to dev branch
      run: git checkout dev
      
    - name: Debug merge commits
      run: |
        echo "Listing merge commits in dev:"
        git log --merges --first-parent dev --oneline
        
    - name: Find merge commit or commits from branch
      id: find_commits
      run: |
        MERGE_COMMIT=$(git log --merges --first-parent dev --grep="Merge branch '${{ steps.normalize.outputs.normalized_branch }}' into dev" --pretty=%H -n 1)
        if [ -z "$MERGE_COMMIT" ]; then
          echo "No merge commit found. Checking for commits from ${{ steps.normalize.outputs.normalized_branch }}..."
          COMMITS=$(git log dev --oneline --grep="${{ steps.normalize.outputs.normalized_branch }}" | awk '{print $1}' | head -n 1)
          if [ -z "$COMMITS" ]; then
            echo "Error: No merge commit or commits from branch '${{ steps.normalize.outputs.normalized_branch }}' found in dev"
            exit 1
          else
            echo "Found commits from ${{ steps.normalize.outputs.normalized_branch }} (possible fast-forward merge)"
            echo "commit_to_revert=$COMMITS" >> $GITHUB_OUTPUT
            echo "is_merge_commit=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "Found merge commit: $MERGE_COMMIT"
          echo "commit_to_revert=$MERGE_COMMIT" >> $GITHUB_OUTPUT
          echo "is_merge_commit=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Configure Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Revert commit
      run: |
        if [ "${{ steps.find_commits.outputs.is_merge_commit }}" = "true" ]; then
          git revert -m 1 ${{ steps.find_commits.outputs.commit_to_revert }} --no-edit
        else
          git revert ${{ steps.find_commits.outputs.commit_to_revert }} --no-edit
        fi
        if [ $? -ne 0 ]; then
          echo "Error: Failed to revert commit ${{ steps.find_commits.outputs.commit_to_revert }}"
          exit 1
        fi
        
    - name: Push revert to dev
      run: |
        # Configure HTTPS URL with PAT
        REPO_URL="https://${{ secrets.PAT }}@github.com/FroCode/Python_Devops.git"
        git remote set-url origin "$REPO_URL"
        git push origin dev
      env:
        GIT_AUTHOR_NAME: "GitHub Actions"
        GIT_AUTHOR_EMAIL: "actions@github.com"
        # Use PAT for authentication
        GIT_ASKPASS: /bin/echo
      continue-on-error: false
        
    - name: Notify success
      run: echo "Successfully reverted commit ${{ steps.find_commits.outputs.commit_to_revert }} from branch '${{ steps.normalize.outputs.normalized_branch }}' in dev"