name: manual-revert-workflow

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch name whose pull request merge commit to revert in dev (e.g., f15)"
        required: true

jobs:
  revert-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper commit lookup
        token: ${{ secrets.PAT }}  # Use PAT for push permissions

    - name: Normalize branch name
      id: normalize
      run: |
        BRANCH_NAME=$(echo "${{ github.event.inputs.branch_name }}" | sed 's#^remotes/origin/##')
        if [[ ! "$BRANCH_NAME" =~ ^[a-zA-Z0-9._-]+$ ]]; then
          echo "Error: Invalid branch name '$BRANCH_NAME'"
          exit 1
        fi
        echo "normalized_branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

    - name: Validate branch exists
      run: |
        if ! git show-ref --quiet refs/remotes/origin/${{ steps.normalize.outputs.normalized_branch }}; then
          echo "Error: Remote branch 'origin/${{ steps.normalize.outputs.normalized_branch }}' does not exist. Available branches:"
          git branch -a
          exit 1
        fi

    - name: Switch to dev branch
      run: git checkout dev

    - name: Debug merge commits
      run: |
        echo "Listing merge commits in dev:"
        git log --merges --first-parent dev --oneline --graph
        echo "Current commit on dev:"
        git log -1 --oneline

    - name: Find merge commit for PR
      id: find_merge_commit
      run: |
        MERGE_COMMIT=""
        for COMMIT in $(git log --merges --first-parent dev --pretty=%H); do
          COMMIT_MESSAGE=$(git log --format=%B -n 1 $COMMIT)
          if echo "$COMMIT_MESSAGE" | grep -q "Merge pull request .* from .*${{ steps.normalize.outputs.normalized_branch }}"; then
            MERGE_COMMIT=$COMMIT
            break
          fi
        done
        if [ -z "$MERGE_COMMIT" ]; then
          echo "Error: No merge commit found for a pull request from branch '${{ steps.normalize.outputs.normalized_branch }}' in dev"
          exit 1
        fi
        echo "Found merge commit: $MERGE_COMMIT"
        echo "commit_to_revert=$MERGE_COMMIT" >> $GITHUB_OUTPUT
        echo "Commit details:"
        git show --summary $MERGE_COMMIT

    - name: Configure Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Attempt revert commit
      id: revert
      run: |
        echo "Attempting to revert merge commit ${{ steps.find_merge_commit.outputs.commit_to_revert }}"
        if ! git revert -m 1 --no-commit ${{ steps.find_merge_commit.outputs.commit_to_revert }}; then
          echo "has_conflict=true" >> $GITHUB_OUTPUT
          git revert --abort
        else
          git commit -m "Revert merge commit ${{ steps.find_merge_commit.outputs.commit_to_revert }} from pull request of ${{ steps.normalize.outputs.normalized_branch }}"
          echo "has_conflict=false" >> $GITHUB_OUTPUT
        fi
      continue-on-error: true

    - name: Handle revert result
      run: |
        if [ "${{ steps.revert.outputs.has_conflict }}" = "true" ]; then
          echo "Creating branch for conflict resolution"
          REVERT_BRANCH="revert-${{ steps.normalize.outputs.normalized_branch }}-${{ github.run_id }}"
          git checkout -b "$REVERT_BRANCH"
          git add .
          git commit -m "Staged revert of ${{ steps.find_merge_commit.outputs.commit_to_revert }} with conflicts"
          git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git push origin "$REVERT_BRANCH"
          echo "Pushed to branch $REVERT_BRANCH for manual conflict resolution"
          echo "Please resolve conflicts in branch $REVERT_BRANCH and create a PR to dev"
          exit 1
        else
          echo "No conflicts, creating PR to dev"
          git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          REVERT_BRANCH="revert-${{ steps.normalize.outputs.normalized_branch }}-${{ github.run_id }}"
          git checkout -b "$REVERT_BRANCH"
          git push origin "$REVERT_BRANCH"
          gh pr create --base dev --head "$REVERT_BRANCH" --title "Revert merge commit ${{ steps.find_merge_commit.outputs.commit_to_revert }} from ${{ steps.normalize.outputs.normalized_branch }}" --body "Automated revert of merge commit ${{ steps.find_merge_commit.outputs.commit_to_revert }} from pull request of ${{ steps.normalize.outputs.normalized_branch }}"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Notify success
      if: steps.revert.outputs.has_conflict != 'true'
      run: echo "Successfully created PR to revert merge commit ${{ steps.find_merge_commit.outputs.commit_to_revert }} from branch '${{ steps.normalize.outputs.normalized_branch }}' in dev"